apiVersion: apps/v1
kind: Deployment
metadata:
  name: isonga-api
  labels:
    app: isonga-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isonga-api
  template:
    metadata:
      labels:
        app: isonga-api
    spec:
      imagePullSecrets:
        - name: isonga-registry

      containers:
        - name: isonga-api
          image: registry.digitalocean.com/isonga-registry/isonga-backend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
          # Inject Secrets
          envFrom:
            - secretRef:
                name: spring-app-secrets
          
          # REMOVED: livenessProbe